use albumsdb;
insert into Albums(title, artist, genre, releaseYear) values("Blonde", "Frank Ocean", "R&B", 2016);
insert into Albums(title, artist, genre, releaseYear) values("Boy in da Corner", "Dizzee Rascal", "Grime", 2003);
insert into Albums(title, artist, genre, releaseYear) values("Care For Me", "Saba", "Rap/Hip-Hop", 2018);
insert into Albums(title, artist, genre, releaseYear) values("Cave World", "Viagra Boys", "Punk", 2022);
insert into Albums(title, artist, genre, releaseYear) values("Die Lit", "Playboi Carti", "Rap/Hip-Hop", 2018);
insert into Albums(title, artist, genre, releaseYear) values("Emotion", "Carly Rae Jepsen", "Pop", 2015);
insert into Albums(title, artist, genre, releaseYear) values("God's Country", "Chat Pile", "Sludge Metal", 2022);
insert into Albums(title, artist, genre, releaseYear) values("Is This It", "The Strokes", "Indie Rock", 2001);
insert into Albums(title, artist, genre, releaseYear) values("Life'll Kill Ya", "Warren Zevon", "Rock", 2000);
insert into Albums(title, artist, genre, releaseYear) values("LP!", "JPEGMAFIA", "Rap/Hip-Hop", 2021);
insert into Albums(title, artist, genre, releaseYear) values("My Beautiful Dark Twisted Fantasy", "Kanye West", "Rap/Hip-Hop", 2010);
insert into Albums(title, artist, genre, releaseYear) values("Nevermind", "Nirvana", "Grunge", 1991);
insert into Albums(title, artist, genre, releaseYear) values("Pinkerton", "Weezer", "Alternative Rock", 1996);
insert into Albums(title, artist, genre, releaseYear) values("Pray for Paris", "Westside Gunn", "Rap/Hip-Hop", 2020);
insert into Albums(title, artist, genre, releaseYear) values("RePorpoised Phantasies", "Machine Girl", "Breakbeat", 2020);
insert into Albums(title, artist, genre, releaseYear) values("Some Rap Songs", "Earl Sweatshirt", "Rap/Hip-Hop", 2018);
insert into Albums(title, artist, genre, releaseYear) values("T H E", "Tricot", "Japanese Math Rock", 2013);
insert into Albums(title, artist, genre, releaseYear) values("Take Off Your Pants and Jacket", "Blink-182", "Pop-Punk", 2001);
insert into Albums(title, artist, genre, releaseYear) values("The Fruit That Ate Itself", "Modest Mouse", "Indie Rock", 1997);
insert into Albums(title, artist, genre, releaseYear) values("Variety", "Mariya Takeuchi", "City Pop", 1984);